### ISSUE TITLE
kkpe.dll 2.18 Link Eyes Components not working in blend shapes 

### ISSUE THREAD

**Issue by Senyu** [IllusionMods/HSPlugins#102]
![CharaStudio-2326946-6cdb745f51e5152037](https://github.com/user-attachments/assets/61949414-f60c-4785-a838-771d30d9cda5)
"Link eyes components" in the newest version 2.18 it is not working.

**Comment by ManlyMarco** [comment]
Is this the same issue as #100? Can you test if the test build posted under that issue fixes this one as well?

**Comment by yarrmateys** [comment]
i tested it since i was about to report this bug, it doesn't fix that.

**Comment by ManlyMarco** [comment]
@ReafLife

**Comment by ReafLife** [comment]
[KKPE.zip](https://github.com/user-attachments/files/18246465/KKPE.zip)
Please check this version

**Comment by yarrmateys** [comment]
the eyes work, but the mouth doesn't, in this version the mouth links to eye parts, breaking animations. the eyes are modified while the mouth is changed, and animations which do mouth/eyes animation with timeline have the mouth broken, ex. the teeth move, but the mouth doesn't. the eyes need to link to cf_O_noseline too.
i'm not sure if mouth should link to its respective mouth elements of teeth, canines and tongue, but if not, an option to do so would be nice, since it's the same thing as with the eyes, the other elements don't look right unless all 4 are modified at the same time, and if it's already modified it won't change, so it shouldn't break things.

**Comment by Senyu** [comment]
@ReafLife what yarrmateys said, in this new version the mouth links to the eye parts.
Thanks  @yarrmateys for helping report this bug.


https://github.com/user-attachments/assets/51be4d1c-07d6-4bd5-b172-624e59e5e7c7

**Comment by ReafLife** [comment]
[KKPE.zip](https://github.com/user-attachments/files/18247404/KKPE.zip)
now link apply only eyecomponents, Are there any other bugs?

**Comment by Senyu** [comment]
Not that I noticed, It has been fixed and seems to be working.
