### ISSUE TITLE
[AI] [Timeline] Add Camera Position and Rotation not working

### ISSUE THREAD

**Issue by kkykkykky** [IllusionMods/HSPlugins#16]
It was brought to my attention by Ionasal on IS Discord server that adding Camera Position or Rotation keyframe to timeline results in null reference exception. A new entry appears under Interpolables but no keyframe gets added.

After a bit of looking, it appears this is only happening in AI Studio and seems to be due to `mainCmaera` not having anything assigned to it. Assigning `Camera.main` to it by patching `Studio.CameraControl.Awake()` brings it in alignment with how it's done in HS2 and fixes the null reference exception. However, I'm not sure if doing this has any negative impact on anything else.

**Comment by ManlyMarco** [comment]
Doing it your way should be fine, can you make a PR with the fix?

**Comment by kkykkykky** [comment]
I made a [small plugin](https://github.com/kkykkykky/AI_AssignMainCamera/blob/main/AI_AssignMainCamera/AssignMainCamera.cs) for this, but never published it outside of my github. I was thinking maybe this could fit under IllusionFixes. To make AI behave more consistently with other games.

**Comment by ManlyMarco** [comment]
@kkykkykky Since other plugins might be affected by this difference, this sounds like a good thing to have in IllusionFixes. Can you make a PR for the plugin? Just update it to reference the common project and use the version from that like other plugins do. You can keep the current GUID so users don't have 2 copies of it running if they installed yours already.
