### ISSUE TITLE
Regarding facial rigidity of characters using Modified Headmod by loading a timeline scene.

### ISSUE THREAD

**Issue by Zeroro066** [IllusionMods/HSPlugins#23]
When I loaded the timeline scene today, I had a problem using a character with the Modified Headmod.
When I load a character using the Modified Head Mod in a timeline scene, the expression becomes stiff and stiff.  Characters with other Headmods started normally, but for some reason, characters with Modified Headmods do not work.  In the future, it would be better to support it and recreate it so that the facial expression moves.  Could you do it in a future mod update?

**Comment by ManlyMarco** [comment]
What do you mean by modified headmod? If you've made a modified copy of an existing headmod, make sure that you don't have any conflicts with the original version (GUID, ID, etc.).

**Comment by ManlyMarco** [comment]
Closing stale issue since it can't be reproduced.

**Comment by GuileGale** [comment]
I'm having the same issue.
Multiple Headmods that drastically alter the face simply do not emote in maker, studio, or the game. Mr.D's work, but that's about it. I haven't altered any of the headmods in any way, and recently updated my game with the latest patch.

**Comment by GuileGale** [comment]
Absolutely not, the mod pages have image after image of all the expressions the headmod can make, but when I load the character, the sliders do literally nothing.

**Comment by ManlyMarco** [comment]
If you're trying to use PE to adjust the blendshapes make sure the stock studio expression toggles aren't overriding it.

**Comment by GuileGale** [comment]
I had to find the blendshapes in the menu and figure out what you were talking about, and they have them, and there aren't any options in the standard kinematics menu for expressions. They're all <- > with no options to them, but the face still won't do anything if I use a blendshape. Is there a toggle or setting I should be enabling in order to use these expressions?

**Comment by ManlyMarco** [comment]
I never really had to mess with those so I can't help much. Try asking in the help channel on the discord server (search for previous similar questions first).

Otherwise for someone to want to fix this you'll have to give exact description of the issue, steps on how to reproduce the issue, versions of affected plugin(s) which introduced the issue and as much other relevant info you can give.
