### ISSUE TITLE
Animations from Kohai, Sonyu or Houshi can't be used as a keyframe in timeline. 

### ISSUE THREAD

**Issue by LRay1** [IllusionMods/HSPlugins#24]
Whenever an animation is added from Houshi, Kohai or  Sonyu as a keyframe and the scene is saved, the next time charastudio is opened and loads the scene the animation keyframe in the timeline will freeze everything but the UI. This only happens when you save the scene, quit studio and reload the scene again. Removing CameraFrameMask helped stop the freeze from happening but it then stops loading the animation. In rare cases it would load a random animation instead.
 
Possible reason: 
This is probably because the timeline uses the resolve ID of the sideloader rather than the ID number of the actual animation when saving the scene. The resolve IDs are changed every time the game is booted. That's why Timeline can't find the animation.

**Comment by LRay1** [comment]
![bug](https://user-images.githubusercontent.com/111369787/185403942-c7185b31-2074-4ed0-9eab-b6624ae5b208.gif)

**Comment by AgiShark** [comment]
The easiest solution might be to add the two words "anime" and "hanime" to [here](https://github.com/IllusionMods/BepisPlugins/blob/8082d08f73df18fcb0e426ec2ca262de1412fc55/src/Core_Sideloader_Studio/Core.Sideloader.Studio.cs#L7) so that Sideloaer tosses the original IDs of the animation zipmods into games.
First of all, there are not many animation zipmods. And not like people enthusiastically release new animation zipmods on a daily/weekly basis. and the same ID can be used in different groups and categories for animation. 
So, There will probably be no side effects. 
For reference, this timeline issue does not occur in HS2/AI studio.
HS2/AI also uses the sideloader, but unlike in KK, the first column of the anime/hanime list is the display order, not the ID numbers. This causes HS2/AI Studio to use the original IDs of the animation zipmods.
This is probably unintentional as randomizing the display order is unlikely to have any ID resolution effect for animation list.

There may be a way to solve this issue by modifying the Timeline.
The Timeline would have to reference the sideloader. and then can use `LoadedStudioResolutionInfo`  [there](https://github.com/IllusionMods/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/BuiltInInterpolables.cs#L290)  and then we will be able to pull Original IDs when saving and Resolved IDs when loading from resolve info.

Anyway I'm not a programmer and just do simple stuff for learning experience and out of curiosity.
While waiting for experienced and knowledgeable coders to step in on this issue, I can give the modified sideloader so you won't run into this timeline issue, at least on your machine.
But I'm not sure if it's a good idea to publicly share an modified and compiled file.
Maybe it is better to wait a little longer.

**Comment by AgiShark** [comment]
The easiest solution might be to add the two words "anime" and "hanime" to [here](https://github.com/IllusionMods/BepisPlugins/blob/8082d08f73df18fcb0e426ec2ca262de1412fc55/src/Core_Sideloader_Studio/Core.Sideloader.Studio.cs#L7) so that Sideloader tosses the original IDs of the animation zipmods into games.
First of all, there are not many animation zipmods. And not like people enthusiastically release new animation zipmods on a daily/weekly basis. and the same ID can be used in different groups and categories for animation.
So, There will probably be no side effects.
For reference, this timeline issue does not occur in HS2/AI studio.
HS2/AI also uses the sideloader, but unlike in KK, the first column of the anime/hanime list is the display order, not the ID numbers. This causes HS2/AI Studio to use the original IDs of the animation zipmods.
This is probably unintentional as randomizing the display order is unlikely to have any ID resolution effect for animation list.

There may be a way to solve this issue by modifying the Timeline.
The Timeline would have to reference the sideloader. and then can use LoadedStudioResolutionInfo [there](https://github.com/IllusionMods/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/BuiltInInterpolables.cs#L290) and then we will be able to pull Original IDs when saving and Resolved IDs when loading from resolve info.

Anyway I'm not a programmer and just do simple stuff for learning experience and out of curiosity.
While waiting for experienced and knowledgeable coders to step in on this issue, I can give the modified sideloader so you won't run into this timeline issue, at least on your machine.
But I'm not sure if it's a good idea to publicly share an modified and compiled file.
Maybe it is better to wait a little longer.

**Comment by ManlyMarco** [comment]
You've got the right idea about the resolve info, and it's probably best to just post the fix instead of waiting since no one else seems to be planning to work on this.

**Comment by LRay1** [comment]
If that solves the problem then i'd really appreciate it!

**Comment by AgiShark** [comment]
https://github.com/AgiShark/HSPlugins/commit/543f51fd483f828a3c185899fcb90cfe0ad15cc8
I felt that similar measures should be taken in [here](https://github.com/AgiShark/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/Timeline.cs#L3636) and [here](https://github.com/AgiShark/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/Timeline.cs#L3612), and I did but I couldn't find a difference between before and after. 
So I left the original code as is.
And it seemed to be more sensitive to unorganized animation zipmods than when I added 2 words to the Sideloader to just use the original IDs of the animation zipmod.
For example, [johnbbob_la_petite]Custom Animations.zipmod contains an unnecessary list file that seems to be for testing.
Unless this list file is cleaned up, [custom]->[dog]->[doggy] keyframe will be skipped after the game is rebooted like before.
But, in the case of the modified sideloader.dll, it is not skipped whether the list file is cleaned or not.

Here you go
[Timeline_v1.1.5_sideloadercompatibility.zip](https://github.com/IllusionMods/HSPlugins/files/9402918/Timeline_v1.1.5_sideloadercompatibility.zip)
.

**Comment by AgiShark** [comment]
https://github.com/AgiShark/HSPlugins/commit/543f51fd483f828a3c185899fcb90cfe0ad15cc8
I felt that similar measures should be taken in [here](https://github.com/AgiShark/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/Timeline.cs#L3636) and [here](https://github.com/AgiShark/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/Timeline.cs#L3612), and I did but I couldn't find a difference between before and after. 
So I left the original code as is.
And it seemed to be more sensitive to unorganized animation zipmods than when I added 2 words to the Sideloader to just use the original IDs of the animation zipmod.
For example, [johnbbob_la_petite]Custom Animations.zipmod contains an unnecessary list file that seems to be for testing.
Unless this list file is cleaned up, [custom]->[dog]->[doggy] keyframe will be skipped after the game is rebooted like before.
But, in the case of the modified sideloader.dll, it is not skipped whether the list file is cleaned or not.

Here you go.
[Timeline_v1.1.5_sideloadercompatibility.zip](https://github.com/IllusionMods/HSPlugins/files/9402934/Timeline_v1.1.5_sideloadercompatibility.zip)

**Comment by LRay1** [comment]
Thanks a lot! I tested it and it worked as intended. Great job! I think that there is still the freeze that will happen if you don't remove the CameraFrameMask so i'll keep this issue open.

**Comment by AgiShark** [comment]
> CameraFrameMask [KK]
> Mask certain ugly frames caused by other plugins during character loading.

This plugin does a prefix patch with `OCIChar.LoadAnime`
So, whenever the LoadAnime method runs, it masks some camera frames to hide some visual glitches.
But what if a plugin calls the LoadAnime method multiple times at very short intervals?

Since I couldn't find any visual glitches yet after removing the plugin, I'm not sure if a more subtle workaround is needed.
But try this modified plugin first. At least it won't freeze the Timeline anymore.
[CameraFrameMask.Koikatu_v1.1_Timelinecompatibility.zip](https://github.com/IllusionMods/HSPlugins/files/9410858/CameraFrameMask.Koikatu_v1.1_Timelinecompatibility.zip)

**Comment by AgiShark** [comment]
`CameraFrameMask` plugin does prefix patch with `LoadAnime`
Whenever the LoadAnime method is called it masks some camera frames to hide the visual glitches.
And with certain conditions satisfied, the Timeline repeatedly calls LoadAnime at very short intervals.
This causes the camera frames to be masked continuously and looks like a freeze.
But I couldn't reproduce this issue with the scene created with the modified Timeline.
So it might be helpful to provide a scene file that can reproduce the issue.
It will help to identify whether or not the issue is an ongoing issue or under what specific conditions it occurs.

**Comment by ManlyMarco** [comment]
@AgiShark 
> I felt that similar measures should be taken in [here](https://github.com/AgiShark/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/Timeline.cs#L3636) and [here](https://github.com/AgiShark/HSPlugins/blob/cc9e321ea45fba62ba0701b8031e89f8e000e403/Timeline.Core/Timeline.cs#L3612), and I did but I couldn't find a difference between before and after.
One way to check if it could help is to make it print out the ID. If the ID is the sideloader range (10000+) then it needs to be resolved.

Are you going to make a PR for the fix? It sounds like it works.

**Comment by AgiShark** [comment]
@ManlyMarco 
Thanks for the tip!
Also the xml files in BepInEx\plugins\Timeline\Single Files
Yes, It needs to be resolved. https://github.com/IllusionMods/HSPlugins/commit/fb5f4fbb04964f852223ef9f4153032d0306bc9a

PR. I've done this because I saw the Kohai stuff there and felt a bit responsibility. 
Eh. I don't know and no sideloader nuget package.

**Comment by LRay1** [comment]
![2022_0818_0140_18_160](https://user-images.githubusercontent.com/111369787/187197030-c646d186-3ef8-4a15-8eec-264a791970a2.png)

I tried putting CameraFrameMask back and load this scene. The freeze still happened unfortunately but again, just removing CameraFrameMask solves my issue. 
The easiest way to set this scene up is to load a map > pick a default character > Put an animation from Kohai, Sonyu or Houshi as a keyframe in Timeline. When the keyframe should play, it will freeze everything but the UI.

**Comment by AgiShark** [comment]
I see, this scene is not a newly created scene using a modified timeline.
In this scene, the original timeline stores the Resolved IDs of the animation clips, not the Original IDs, in the scene PNG file. 
So, if you load this scene and try to play the animation clip keyframe, Timeline cannot find the animation clip corresponding to the keyframe and camera masking spam occurs together with the CameraFrameMask Plugin.
Currently, This happens when the timeline cannot play/find the animation clip corresponding to that keyframe. 
Like when you are trying to play a scene with animation zipmods keyframes saved using the **original** timeline. Or when you  keyframed animation clips of the animation zipmod with list files not properly cleaned up.

**Comment by LRay1** [comment]
So I used the new timeline zip you added and remade the scene. It didn't freeze this time! And it also remembered the animation the next time I loaded the scene. Thank you so much! I think with that the issue is fully solved.
